(ns resync
  "Re-sync the demos from a raylib-jlt checkout (`bb resync`).

  While the migration is in progress raylib-jlt stays the source of truth for
  the example code, so this copies it across again:

  - every example with a `-m net.b12n.raylib-jlt.<name>` alias in raylib-jlt's
    deps.edn becomes <name>/src/net/b12n/raylib_jlt/<name>.clj, overwritten
  - app.clj and reasings.clj go to common/, overwritten
  - <name>/deps.edn and <name>/bb.edn are written only when missing, so edits
    to them survive
  - the root deps.edn and check.clj are regenerated from the demo directories
    present here, so a demo added by hand keeps its alias and its :check entry
  - <name>/docs/guide/index.md is regenerated from raylib-jlt's gallery entry,
    the example's ns docstring and the guide pages that mention it, and its
    recording is copied to <name>/docs/demos/
  - demos.edn and the per-demo tasks in bb.edn (between its BEGIN/END
    markers) are regenerated, so `bb <demo>` exists for every demo

  Usage: bb resync [--dry-run] [path-to-raylib-jlt]
  The path defaults to ../raylib-jlt."
  (:require
   [babashka.fs :as fs]
   [clojure.edn :as edn]
   [clojure.string :as str]))

(def root (str (fs/parent (fs/parent (fs/absolutize *file*)))))

(def ns-prefix "net.b12n.raylib-jlt.")

;; In common/ rather than a demo of their own: neither has a -main.
(def common-files ["app.clj" "reasings.clj"])

;; The hand-written tasks in bb.edn. A demo with one of these names gets no task
;; of its own, though `bb run <demo>` still reaches it.
(def ^:private fixed-tasks #{"info" "list" "run" "run-all" "check" "doctor" "resync"})

(defn- ->file [name] (str (str/replace name "-" "_") ".clj"))

(defn- upstream-aliases
  "{demo-name alias-name} for every runnable example in raylib-jlt's deps.edn.
  The alias usually equals the name. The basic-window example is core/:run."
  [src-root]
  (into {}
        (for [[alias {:keys [main-opts]}] (:aliases (edn/read-string (slurp (fs/file src-root "deps.edn"))))
              :let [[flag ns-str] main-opts]
              :when (and (= "-m" flag)
                         (string? ns-str)
                         (str/starts-with? ns-str ns-prefix)
                         (not= alias :check))]
          [(subs ns-str (count ns-prefix)) (name alias)])))

(defn- demo-deps-edn [name]
  (str "{:jolt/min-version \"0.8.0\"\n"
       " :paths [\"src\"]\n"
       " :deps {net.b12n/raylib                  {:local/root \"../../raylib-jlt/lib\"}\n"
       "        net.b12n/raylib-jolt-demo-common {:local/root \"../common\"}}\n"
       " :aliases {:run {:main-opts [\"-m\" \"" ns-prefix name "\"]}}}\n"))

(defn- demo-bb-edn [name desc]
  (str ";; Run this demo from here with `bb run` or `jolt run`. From the repo root it's\n"
       ";; `bb " name "`. Written by `bb resync` when missing; edits survive.\n"
       "{:tasks\n"
       " {:requires ([babashka.fs :as fs])\n"
       "  :init (def jolt-cmd (if (fs/which \"jolt\") \"jolt\" \"joltc\"))\n"
       "  run {:doc " (pr-str (str "▶ " (or desc name))) "\n"
       "       :override-builtin true\n"
       "       :task (let [{:keys [exit]} (shell {:continue true} jolt-cmd \"-M:run\")]\n"
       "               (when-not (zero? exit) (System/exit exit)))}}}\n"))

(defn- local-demos
  "Demo names: every directory here with a deps.edn and its example source."
  []
  (sort (for [d (fs/list-dir root)
              :let [name (str (fs/file-name d))]
              :when (and (fs/exists? (fs/file d "deps.edn"))
                         (fs/exists? (fs/file d "src/net/b12n/raylib_jlt" (->file name))))]
          name)))

(defn- root-deps-edn [demos alias-of]
  (let [w (inc (apply max (map (comp count alias-of) demos)))
        pad (fn [s] (format (str "%-" w "s") s))
        check-deps (str/join "\n" (for [n demos]
                                    (str "                   net.b12n.raylib-jolt-demo/" n " {:local/root \"" n "\"}")))
        aliases (str/join "\n" (for [n demos]
                                 (str "  " (pad (str ":" (alias-of n)))
                                      " {:extra-deps {net.b12n.raylib-jolt-demo/" n " {:local/root \"" n "\"}}\n"
                                      "  " (pad "") "  :main-opts [\"-m\" \"" ns-prefix n "\"]}")))]
    (str ";; Root of the raylib-jolt-demo suite. Every demo is its own sub-project\n"
         ";; (<demo>/deps.edn) and runs from there with `jolt -M:run`. From this directory\n"
         ";; each one runs under the alias name it had in raylib-jlt, e.g.\n"
         ";; `jolt -M:asteroids`. `jolt -M:check` compiles every demo with no window.\n"
         ";;\n"
         ";; Generated by `bb resync` from the demo directories present here. Don't\n"
         ";; hand-edit the aliases: add the demo directory and re-run it instead.\n"
         "{:jolt/min-version \"0.8.0\"\n"
         " :paths [\"src\"]\n"
         " :deps {net.b12n/raylib                  {:local/root \"../raylib-jlt/lib\"}\n"
         "        net.b12n/raylib-jolt-demo-common {:local/root \"common\"}}\n"
         " :aliases\n"
         " {:check {:extra-deps {" (str/triml check-deps) "}\n"
         "          :main-opts [\"-m\" \"net.b12n.raylib-jolt-demo.check\"]}\n"
         "\n"
         aliases "}}\n")))

(defn- check-clj [demos]
  (let [nss (sort (concat (map #(str/replace % ".clj" "") (map #(str/replace % "_" "-") common-files))
                          demos))]
    (str "(ns net.b12n.raylib-jolt-demo.check\n"
         "  \"Headless compile-check (`jolt -M:check` from the repo root).\n"
         "\n"
         "  Requires every demo namespace, which compiles each one WITHOUT opening a\n"
         "  window. It does not exercise rendering; each demo's own\n"
         "  `RAYLIB_APP_AUTO_QUIT_MS` + `RAYLIB_APP_SHOT` smoke does that.\"\n"
         "  (:require\n"
         (str/join "\n" (for [n nss] (str "   [" ns-prefix n "]")))
         "))\n"
         "\n"
         "(defn -main [& _]\n"
         "  (println \"OK: every demo namespace compiled\"))\n")))

;; --- per-demo docs ------------------------------------------------------------
(def upstream-guide-url "https://github.com/jlt-commons/raylib-jlt/blob/main/docs/guide/")

;; Both list every example, so a mention there says nothing about one of them.
(def ^:private catalog-pages #{"demos.md" "example-catalog.md"})

(defn- registry
  "{alias {:display .. :category .. :blurb ..}} from raylib-jlt's
  scripts/examples_registry.clj, the source its gallery is built from. The
  recordings are named by display name, which for the oldest twelve examples
  is not the alias (bounce is bouncing-ball, run is basic-window)."
  [src-root]
  (load-file (str (fs/file src-root "scripts/examples_registry.clj")))
  (into {} (for [[display alias group desc] @(resolve 'examples-registry/examples)]
             [alias {:display display :category group :blurb desc}])))

(defn- docstring
  "The example's ns docstring with the continuation-line indent removed."
  [src]
  (let [[_ _ doc] (read-string src)]
    (when (string? doc)
      (let [[head & tail] (str/split-lines doc)
            indent (->> tail (remove str/blank?) (map #(count (re-find #"^ *" %))) (apply min 0x7fffffff))
            indent (if (= indent 0x7fffffff) 0 indent)]
        (str/join "\n" (cons head (map #(if (str/blank? %) "" (subs % (min indent (count %)))) tail)))))))

(defn- guide-pages
  "[[file title text] ...] for raylib-jlt's guide pages, minus the catalogs."
  [src-root]
  (for [f (sort (map str (fs/glob (fs/file src-root "docs/guide") "*.md")))
        :let [file (str (fs/file-name f))]
        :when (not (catalog-pages file))
        :let [text (slurp f)]]
    [file (str/trim (subs (or (re-find #"(?m)^# .*$" text) (str "# " file)) 2)) text]))

(defn- mentions?
  "Does a guide page name this example by namespace, alias, bb task or file?"
  [text name alias display]
  (let [b "(?![a-z0-9-])"
        q java.util.regex.Pattern/quote]
    (boolean (re-find (re-pattern (str "raylib-jlt\\." (q name) b
                                       "|-M:" (q alias) b
                                       "|bb " (q display) b
                                       "|" (q (->file name))))
                      text))))

(defn- demo-guide [{:keys [name alias category blurb media doc pages]}]
  (str "<!-- Generated by `bb resync` from raylib-jlt. Edits here are overwritten. -->\n"
       "# " name "\n"
       "\n"
       (when blurb (str blurb "\n\n"))
       (when category (str "Category: " category "\n\n"))
       (when media (str "![" name "](../demos/" media ")\n\n"))
       "## Run it\n"
       "\n"
       (let [here (str "cd " name " && bb run")
             there (str "bb " (if (fixed-tasks name) (str "run " name) name))
             w (max (count here) (count there))]
         (str "```sh\n"
              (format (str "%-" w "s") here) "   # from this demo (or jolt run, jolt -M:run)\n"
              (format (str "%-" w "s") there) "   # from the repo root (or jolt -M:" alias ")\n"
              "```\n"))
       (when doc (str "\n## About\n\n" doc "\n"))
       (when (seq pages)
         (str "\n## Background in the raylib-jlt guide\n\n"
              (str/join (for [[file title] pages]
                          (str "- [" title "](" upstream-guide-url file ")\n")))))))

(defn- sync-file!
  "Write `content` to `path` when it differs. Returns :created, :updated or nil."
  [dry-run? path content]
  (let [f (fs/file path)
        old (when (fs/exists? f) (slurp f))]
    (when (not= old content)
      (when-not dry-run?
        (fs/create-dirs (fs/parent f))
        (spit f content))
      (if old :updated :created))))

;; --- bb.edn registry and per-demo tasks ---------------------------------------
(def ^:private begin-marker "  ;; BEGIN per-demo tasks, generated by `bb resync`\n")
(def ^:private end-marker "  ;; END per-demo tasks\n")

(defn- demo-entries
  "One map per demo for demos.edn. :old-name only where raylib-jlt's bb task
  name differs, so `bb run bouncing-ball` keeps working."
  [demos alias-of shows]
  (for [n demos
        :let [{:keys [display category blurb]} (get shows (alias-of n))]]
    (apply array-map (concat [:name n :alias (alias-of n)]
                             (when (and display (not= display n)) [:old-name display])
                             (when category [:category category])
                             (when blurb [:desc blurb])))))

(defn- demos-edn [entries]
  (str ";; Every demo, for bb.edn's tasks. Generated by `bb resync`; edits are overwritten.\n"
       "[" (str/join "\n " (map pr-str entries)) "]\n"))

(defn- bb-edn-with-tasks
  "bb.edn's text with the block between the markers replaced, or nil when the
  markers are missing."
  [text entries]
  (let [b (str/index-of text begin-marker)
        e (some-> b (->> (str/index-of text end-marker)))]
    (when (and b e)
      (let [named (remove (comp fixed-tasks :name) entries)
            w (apply max (map (comp count :name) named))]
        (str (subs text 0 (+ b (count begin-marker)))
             (str/join (for [{:keys [name desc]} named]
                         (str "  " (format (str "%-" w "s") name)
                              " {:doc " (pr-str (str "▶ " (or desc name)))
                              " :task (exit-with (run-demo " (pr-str name) "))}\n")))
             (subs text e))))))

(defn -main [& args]
  (let [dry-run? (some #{"--dry-run"} args)
        src-root (str (fs/normalize (fs/absolutize (or (first (remove #{"--dry-run"} args))
                                                       (fs/file root ".." "raylib-jlt")))))
        src-dir (fs/file src-root "src/net/b12n/raylib_jlt")
        _ (when-not (fs/exists? (fs/file src-root "deps.edn"))
            (binding [*out* *err*] (println "No raylib-jlt deps.edn under" src-root))
            (System/exit 1))
        upstream (upstream-aliases src-root)
        shows (registry src-root)
        pages (guide-pages src-root)
        changes (atom [])
        sync! (fn [path content]
                (when-let [what (sync-file! dry-run? path content)]
                  (swap! changes conj [what (str (fs/relativize root path))])))]
    (doseq [f common-files]
      (sync! (fs/file root "common/src/net/b12n/raylib_jlt" f) (slurp (fs/file src-dir f))))
    (doseq [[name alias] (sort upstream)
            :let [src (slurp (fs/file src-dir (->file name)))
                  display (get-in shows [alias :display] name)
                  ;; Saved under the demo's own name here, whatever upstream called it.
                  ext (first (for [ext ["gif" "png"]
                                   :when (fs/exists? (fs/file src-root "docs/demos" (str display "." ext)))]
                               ext))
                  media (when ext (str name "." ext))]]
      (sync! (fs/file root name "src/net/b12n/raylib_jlt" (->file name)) src)
      (when-not (fs/exists? (fs/file root name "deps.edn"))
        (sync! (fs/file root name "deps.edn") (demo-deps-edn name)))
      (when-not (fs/exists? (fs/file root name "bb.edn"))
        (sync! (fs/file root name "bb.edn") (demo-bb-edn name (get-in shows [alias :blurb]))))
      ;; Binary, so compare bytes rather than going through sync!'s slurp.
      (when media
        (let [from (fs/file src-root "docs/demos" (str display "." ext))
              to (fs/file root name "docs/demos" media)]
          (when-not (and (fs/exists? to)
                         (java.util.Arrays/equals (fs/read-all-bytes from) (fs/read-all-bytes to)))
            (swap! changes conj [(if (fs/exists? to) :updated :created) (str (fs/relativize root to))])
            (when-not dry-run?
              (fs/create-dirs (fs/parent to))
              (fs/copy from to {:replace-existing true})))))
      (sync! (fs/file root name "docs/guide/index.md")
             (demo-guide (merge (get shows alias)
                                {:name name :alias alias :media media :doc (docstring src)
                                 :pages (filter (fn [[_ _ text]] (mentions? text name alias display)) pages)}))))
    ;; On a dry run the new demos aren't on disk yet, so count them in by hand.
    (let [demos (sort (distinct (concat (local-demos) (keys upstream))))
          alias-of #(get upstream % %)]
      (sync! (fs/file root "deps.edn") (root-deps-edn demos alias-of))
      (sync! (fs/file root "src/net/b12n/raylib_jolt_demo/check.clj") (check-clj demos))
      (let [entries (demo-entries demos alias-of shows)
            bb-edn (fs/file root "bb.edn")]
        (sync! (fs/file root "demos.edn") (demos-edn entries))
        (if-let [text (bb-edn-with-tasks (slurp bb-edn) entries)]
          (sync! bb-edn text)
          (println "bb.edn has no BEGIN/END per-demo tasks markers, so its tasks were left alone"))
        (when-let [clash (seq (filter fixed-tasks demos))]
          (println "No task of their own (name taken by a bb.edn task):" (str/join " " clash))))
      (doseq [[what path] @changes]
        (println (if dry-run? (str "would be " (clojure.core/name what)) (clojure.core/name what)) path))
      (let [local-only (remove (set (keys upstream)) demos)]
        (when (seq local-only)
          (println "Not in raylib-jlt (kept, not synced):" (str/join " " local-only))))
      (println (str (count demos) " demos, " (count @changes) " file(s) "
                    (if dry-run? "would change" "changed")
                    " from " src-root)))))

(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
